### ISSUE TITLE
Binary Recycle Failure when opening the Gallery project.

### ISSUE THREAD

**Issue by AnthonyMastrean** [FubuMvcArchive/storyteller#14]
I've done a fresh Clone and build and started StoryTellerUI. I switched to the Settings tab and click the Gallery link, the following Binary Recycle Failure is thrown.

System.ArgumentNullException: Value cannot be null.
Parameter name: assemblyString

Server stack trace: 
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at StoryTeller.Execution.FixtureAssembly.find() in C:\Users\anthony.mastrean\Documents\Visual Studio 2010\Projects\StoryTeller\source\StoryTeller\Execution\FixtureAssembly.cs:line 49
   at StoryTeller.Execution.FixtureAssembly.get_System() in C:\Users\anthony.mastrean\Documents\Visual Studio 2010\Projects\StoryTeller\source\StoryTeller\Execution\FixtureAssembly.cs:line 74
   at StoryTeller.Execution.TestRunnerProxy.StartSystem(FixtureAssembly fixtureAssembly, MarshalByRefObject remotePublisher) in C:\Users\anthony.mastrean\Documents\Visual Studio 2010\Projects\StoryTeller\source\StoryTeller\Execution\TestRunnerProxy.cs:line 76
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at StoryTeller.Execution.TestRunnerProxy.StartSystem(FixtureAssembly fixtureAssembly, MarshalByRefObject remotePublisher)
   at StoryTeller.Execution.TestRunnerDomain.LoadProject(IProject project) in C:\Users\anthony.mastrean\Documents\Visual Studio 2010\Projects\StoryTeller\source\StoryTeller\Execution\TestRunnerDomain.cs:line 33

**Comment by jeremydmiller** [comment]
Long gone.
