### ISSUE TITLE
UI crashes clicking on pretty much anything in Win7 64

### ISSUE THREAD

**Issue by paulio** [FubuMvcArchive/storyteller#16]
Clicking on the buttons seems to just crash the application or show a number of exceptions, perhaps I've missed some install instruction?

**Comment by storyteller** [comment]
You've got to put in a lot more context than "it crashes."  I've used the StoryTeller UI extensively on Windows 7 64 bit and obviously didn't see crashes in the current code before releasing.

**Comment by paulio** [comment]
Didn't mean to be lazy, but just about anything crashes it; I'll expand:
E.g
1. Open StoryTellerUI.exe
2. Click 'View All Test' or 'Acceptance' or 'Regression', etc - Windows pops up the following and the app crashes out - System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at FubuCore.Util.Cache`2.FillDefault(TKey key)
   at FubuCore.Util.Cache`2.get_Item(TKey key)
   at StoryTeller.UserInterface.Exploring.TestExplorer.NodeFor(Suite suite)
   at StoryTeller.UserInterface.Exploring.TestExplorer.ResetFilter()
   at StoryTeller.UserInterface.Exploring.TestExplorer.LifecycleChanged(Lifecycle lifecycle)
   at StoryTeller.UserInterface.Controls.TestFilterBar.<.ctor>b__3(Lifecycle x)
   at StoryTeller.UserInterface.Controls.ToggleBar`1.selectValue(T value, ToggleButton button)
   at StoryTeller.UserInterface.Controls.ToggleBar`1.ConfigureToggleBar.<>c__DisplayClassb.<>c__DisplayClassd.<Text>b__a(Object a, RoutedEventArgs b)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate cat

**Comment by storyteller** [comment]
Just tried it and it worked just fine.  Where did you get the code from?  You aren't on an old Tigris build are you?  Is there a project loaded when you do this?

**Comment by paulio** [comment]
Yes there is a project preloaded when it opens

**Comment by paulio** [comment]
Any news on this?

**Comment by jeremydmiller** [comment]
Once again, I cannot reproduce whatever it was that was happening to you.  I've used that functionality with ZERO problems since this time.  Can you zip up and email me the configuration & code you were using?
